### ISSUE TITLE
Wrong property google_container_cluster.tezos_baker.region

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#11]
There is a problem at
https://github.com/hodl-dot-farm/tezos-on-gke/blob/45053a0862bf97f0525862c411fa4da5d59ac397/terraform/k8s.tf#L70

Where "region" should be "location".

https://github.com/hodl-dot-farm/tezos-on-gke/blob/989ca3b08baf4f2cadc37ee73a788d4d304b3a1d/terraform/gcp.tf#L164

**Comment by hodl-dot-farm** [comment]
Can you clarify ?
google_container_cluster.tezos_baker.region
is a valid attribute.
I upgraded my gcloud terraform provider to be sure, and it works fine on my
end. What is the problem with the current code exactly ?

**Comment by denver-s** [comment]
I had this problem even months ago.
The error that I receive is that the variable has a null value and I figured out it was a different name so I changed to location and it worked.

**Comment by denver-s** [comment]
It's seems to be fixed now.
