### ISSUE TITLE
Reducing private node storage size

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#15]
Currently private node has a [90 GBi storage volume](https://github.com/midl-dev/tezos-on-gke/blob/7dc3a8404d47016e3219f8483feb9b3595da4adc/k8s/tezos-private-node-deployment.yaml#L21). Could it be reduced in order so save some money?

This is my ` tezos-private-baking-node` on GCP:
![image](https://user-images.githubusercontent.com/31325316/84260372-35e63480-ab1a-11ea-9e74-39e1a06bfb12.png)

**Comment by nicolasochem** [comment]
Next version will have prometheus monitoring, so then I can set up an alert when the disk utilization grows close to the limit. Then we can reduce the default size.

**Comment by denver-s** [comment]
I see that it's been implemented here: https://github.com/midl-dev/tezos-on-gke/commit/5c1200139b74fc3c575a0bb8d7014006cc18d11a

I am testing a 30Gi private node and it's fine, but 40Gi is reasonable.

**Comment by nicolasochem** [comment]
Yes, besides if you set up slack alerts, you will now get alerted when you are getting close to full, so you can resize the volume. Thanks for the suggestion.
