### ISSUE TITLE
Use Tezos GigaNode snapshots

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#16]
I suggest to use the new snapshots feature by Tezos GigaNode:

https://snapshots-tezos.giganode.io/

**Comment by goodpen** [comment]
what is the difference?

**Comment by denver-s** [comment]
They are taken at more recent blocks. Example, right now:
- block 1017320 on Tezos GigaNode
- block 969823 on Phlogi

**Comment by nicolasochem** [comment]
Makes sense, I'll look into it.

**Comment by nicolasochem** [comment]
I have restored the ability to provide URL. The tulip-tools snapshots work well in this model, and they are updated every 3 days. Works for Carthagenet too.

**Comment by denver-s** [comment]
Fine for me.
