### ISSUE TITLE
Error when deploying with terraform

### ISSUE THREAD

**Issue by marianogadea** [midl-dev/tezos-on-gke#20]
Hi, I'm having the following error when deploying docker image:

local_file.k8s_kustomization: Creation complete after 0s [id=0728e4ecd9dbc70fc144a0e57fdc92a56293af0d]
null_resource.push_containers: Provisioning with 'local-exec'...
null_resource.push_containers (local-exec): Executing: ["/bin/sh" "-c" "\nset -x\n\nbuild_container () {\n  set -x\n  cd $1\n  container=$(basename $1)\n  cp Dockerfile.template Dockerfile\n  sed -i \"s/((tezos_sentry_version))/latest-release/\" Dockerfile\n  sed -i \"s/((tezos_private_version))/latest-release/\" Dockerfile\n  cat << EOY > cloudbuild.yaml\nsteps:\n- name: 'gcr.io/cloud-builders/docker'\n  args: ['build', '-t', \"gcr.io/my-tezos-project/$container:latest\", '.']\nimages: [\"gcr.io/my-tezos-project/$container:latest\"]\nEOY\n  gcloud builds submit --project my-tezos-project --config cloudbuild.yaml .\n  rm -v Dockerfile\n  rm cloudbuild.yaml\n}\nexport -f build_container\nfind ./../docker -mindepth 1 -type d -exec bash -c 'build_container \"$0\"' {} \\; -printf '%f\\n'\n"]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Creating...
null_resource.push_containers (local-exec): + export -f build_container
null_resource.push_containers (local-exec): /bin/sh: 21: export: Illegal option -f

module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [10s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [20s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [30s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [40s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [50s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [1m0s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [1m10s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [1m20s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [1m30s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [1m40s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [1m50s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Still creating... [2m0s elapsed]
module.terraform-gke-blockchain.google_container_node_pool.blockchain_cluster_node_pool: Creation complete after 2m5s [id=projects/my-tezos-project/locations/us-central1/clusters/blockchain/nodePools/tzbaker-pool]

Error: Error running command '
set -x

build_container () {
  set -x
  cd $1
  container=$(basename $1)
  cp Dockerfile.template Dockerfile
  sed -i "s/((tezos_sentry_version))/latest-release/" Dockerfile
  sed -i "s/((tezos_private_version))/latest-release/" Dockerfile
  cat << EOY > cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', "gcr.io/my-tezos-project/$container:latest", '.']
images: ["gcr.io/my-tezos-project/$container:latest"]
EOY
  gcloud builds submit --project my-tezos-project --config cloudbuild.yaml .
  rm -v Dockerfile
  rm cloudbuild.yaml
}
export -f build_container
find ./../docker -mindepth 1 -type d -exec bash -c 'build_container "$0"' {} \; -printf '%f\n'
': exit status 2. Output: + export -f build_container
/bin/sh: 21: export: Illegal option -f

**Comment by nicolasochem** [comment]
I fixed it in this branch https://github.com/midl-dev/tezos-on-gke/tree/repo_as_module

you can either switch to this branch (which should be working) or just fix the code by hand

just set the interpreter this way
https://github.com/midl-dev/tezos-on-gke/blob/repo_as_module/terraform/k8s.tf#L71

**Comment by nicolasochem** [comment]
The fixes have been merged.
