### ISSUE TITLE
Error when deploying cluster first time without authorized_signer

### ISSUE THREAD

**Issue by marianogadea** [midl-dev/tezos-on-gke#25]
When deploying for fist time cluster without authorized_signer got following error:

Error: Error in function call: Call to function "templatefile" failed: ./../k8s/tezos-remote-signer-loadbalancer-tmpl/kustomization.yaml.tmpl:17,76-79: Invalid index; The given key does not identify an element in this collection value..

Note that instructions mention "Note that authorized_signers is empty for now." like below:

baking_nodes = {
  mynode = {
    mybaker = {
      public_baking_key="tz1YmsrYxQFJo5nGj4MEaXMPdLrcRf2a5mAU"
      ledger_authorized_path="ledger://my-four-key-words/ed25519/0h/1h",
      authorized_signers : []

    }
  }
}

**Comment by nicolasochem** [comment]
It looks like these instructions are not accurate. You should then put placeholder content in authorized signers, such as your own public ssh key, and a port number. Once the signer is actually provisioned, replace the ssh pubkey with the actual one and apply. I will fix the documentation.

**Comment by marianogadea** [comment]
Solved with your solution, thanks!
