### ISSUE TITLE
Public reserved IP for load balancer not bound

### ISSUE THREAD

**Issue by marianogadea** [midl-dev/tezos-on-gke#26]
when deploying cluster the reserved address is not bound to the loadbalancer, instead an ephemeral IP is bound:
![image](https://user-images.githubusercontent.com/29900138/91565027-eee92d80-e917-11ea-92c4-a498d287e803.png)
![image](https://user-images.githubusercontent.com/29900138/91565089-06c0b180-e918-11ea-8428-dc0644713eba.png)

**Comment by nicolasochem** [comment]
That may be because your tezos-signer-forwarder container is not running currently?

**Comment by marianogadea** [comment]
No, tezos-signer-forwarder container was running. I destroyed and redeployed a couple of times with same result.
