### ISSUE TITLE
sshd: no hostkeys available -- exiting

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#29]
In `variables.tf` I did not set any `signer_target_host_key` as I did not understand what it is and how to generate, furthermore it seemed optional. My pod `tezos-remote-signer-forwarder-mybaker-0` gives me this error:

![image](https://user-images.githubusercontent.com/31325316/98574626-722fe380-22b8-11eb-80f5-d235bc201d48.png)

**Comment by nicolasochem** [comment]
It's explained here, but yes, the README should be more clear

https://tezos-docs.midl.dev/deploy-remote-signer.html#ssh-endpoint-host-key

**Comment by denver-s** [comment]
For now I commented [this line](https://github.com/midl-dev/tezos-on-gke/blob/c9bbe9b9b410e0b2bfd74cfc734753e42a57b64d/docker/tezos-remote-signer-forwarder/tezos-remote-signer-forwarder.sh#L4) of tezos-remote-signer-forwarder.sh to make it work.

**Comment by nicolasochem** [comment]
ok, but I am not sure if it will work without the host key. You should generate one, so if your cluster breaks for any reason, and you recreate it, your signer will connect to it as if nothing happened... in the absence of this, it will refuse to connect.

By the way, this is the source code for the docs. Feel free to open PRs, you can do it directly on github.

https://github.com/midl-dev/tezos-suite-docs/

**Comment by denver-s** [comment]
Yes, I will generate a host key. I was wondering if there is a guide to it or is it just a `ssh-keygen` command to execute on my terminal.

> By the way, this is the source code for the docs. Feel free to open PRs, you can do it directly on github.

Thank you, I will.

**Comment by nicolasochem** [comment]
I didn't write it down, I'd appreciate if you add it to the guide. Something like:

https://serverfault.com/a/471346/80321

**Comment by denver-s** [comment]
Thanks. I did this way, deleted the pod and it worked!

```
variable "signer_target_host_key" {
  type = string
  default = <<-EOK
-----BEGIN OPENSSH PRIVATE KEY-----
<the key>
-----END OPENSSH PRIVATE KEY-----
EOK
}
```

**Comment by denver-s** [comment]
@nicolasochem As a side note, it's probably needed to perform a check of non-optional values before Terraform execution.

**Comment by nicolasochem** [comment]
But the terraform module can also be used as public node only, or baker
without a remote signer, in which case the host key is not mandatory.

**Comment by denver-s** [comment]
Mmm I see. Still, I think some kind of checks need to be implemented.
