### ISSUE TITLE
Errore creating zone with Cloudflare because it already exists

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#3]
I manually created a zone for the website (I thought it wasn't necessary!) on my Cloudflare and so it gives me this error.

```
Error: Error creating zone "[DOMAIN]": error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1061,\"message\":\"[DOMAIN] already exists\"}],\"messages\":[],\"result\":null}"

  on cloudflare.tf line 12, in resource "cloudflare_zone" "tezos_baker_zone":
  12: resource "cloudflare_zone" "tezos_baker_zone" {
```

**Comment by hodl-dot-farm** [comment]
I think it's not necessary to pre-create the zone. Delete it and apply again, the cloudflare terraform provider will create it entirely.

**Comment by denver-s** [comment]
The fact is that I don’t want a website and I tried everything in order to not let Terraform create the zone: I didn’t provide “website” and “website_archive” (which I am not sure what it is) but it still asked for CloudFlare account, so I gave it but then I had to create the website.
I’m a little confused 😅

**Comment by hodl-dot-farm** [comment]
@denver-s I see. I have been thinking about making the website part optional, so you could just create a baker without the website. It's not a big priority since the codebase works for me but I'll consider it.
