### ISSUE TITLE
Cannot add second signer if tezos-baker-lb was previosly created

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#33]
Error is:

`Error: Error creating Address: googleapi: Error 409: The resource 'projects/xyxyxy/regions/us-central1/addresses/tezos-baker-lb' already exists, alreadyExists`

Steps to reproduce:

1. deploy infrastructure using only one signer (in variables.tf)
2. add another signer data to the variables.tf config
3. error

https://github.com/midl-dev/tezos-on-gke/blob/c9bbe9b9b410e0b2bfd74cfc734753e42a57b64d/terraform/k8s.tf#L53

**Comment by denver-s** [comment]
It's probably [this commit](https://github.com/midl-dev/tezos-on-gke/commit/f960bda4ba3e1a7f7cd81845cf4e4d96660ae444#diff-50dd05adb6e980fac10f540e0e8b504e00b373ea06b4c7168cb08bd974fe1003) that caused the error. I tried with a completely new project and it gives the exact error.

**Comment by hodl-dot-farm** [comment]
Thanks, I saw the same problem when I was creating one delphinet namespace
and one mainnet namespace in the same k8s cluster.

**Comment by denver-s** [comment]
Is it correct to say that v1.2 does not allow two remote signers then?

**Comment by hodl-dot-farm** [comment]
It's likely. I didn't test in this configuration.
Could you please test PR#35 and report?

**Comment by denver-s** [comment]
I get this error:

```
error: AccumulateTarget: conflict between map[string]interface {}{"apiVersion":"v1", "kind":"Service", "metadata":map[string]interface {}{"name":"tezos-remote-signer-forwarding-ingress"}, "spec":map[string]interface {}{"loadBalancerIP":"xx.xx.xx.xx", "ports":[]interface {}{map[string]interface {}{"name":"ssh-mybaker-0", "port":58255}}}} and map[string]interface {}{"apiVersion":"v1", "kind":"Service", "metadata":map[string]interface {}{"name":"tezos-remote-signer-forwarding-ingress"}, "spec":map[string]interface {}{"loadBalancerIP":"xx.xx.xx.xx", "ports":[]interface {}{map[string]interface {}{"name":"ssh-mybaker-1", "port":58255}}}}
```

**Comment by nicolasochem** [comment]
I think that's because you are using the same port for both signers.
The LB IP is shared to save money, consequently each Ingress is tied to a
different port.

**Comment by denver-s** [comment]
Should I change it to something like this? Bold is the different port.

```
authorized_signers = [
          {
            ssh_pubkey = "ssh-rsa xxxxx
            signer_port = 8443
            tunnel_endpoint_port = 58255
          }
          ,
          {
            ssh_pubkey = "ssh-rsa yyyyyy
            signer_port = 8444
            tunnel_endpoint_port = **58256**
          }
]
```

**Comment by nicolasochem** [comment]
Yes, your config looks good.

**Comment by denver-s** [comment]
Here you expose only 58255. Is it normal?

https://github.com/midl-dev/tezos-on-gke/blob/464f0e12684917322811981ff4d02106d8074244/docker/tezos-remote-signer-forwarder/Dockerfile.template#L27

**Comment by nicolasochem** [comment]
Good point. I think this line has no effect. I am using ports different
than 58255 in prod right now with 1.2 release. Let me remove it.

**Comment by denver-s** [comment]
It worked!

Note to everyone: you also need to set the same port [on your remote signer](https://github.com/midl-dev/tezos-remote-signer-os/blob/master/tezos-remote-signer.yaml).

**Comment by denver-s** [comment]
@nicolasochem the fix for seems to be gone in v2. I can't even find the commit on the master branch now.

**Comment by nicolasochem** [comment]
Thank you for your prompt feedback. I have re-added the fix.
