### ISSUE TITLE
Error 403: Compute Engine API has not been used in project [...] before or it is disabled.

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#34]
```Error: Error when reading or editing Subnetwork Not Found : default: googleapi: Error 403: Compute Engine API has not been used in project [xxxx] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=[xxxx] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured```

**Comment by hodl-dot-farm** [comment]
You can wait a few minutes and do terraform plan/apply again. I yet have to
find way for terraform to gracefully handle this.

**Comment by denver-s** [comment]
Quick fix:

- create a project
- go to IAM settings
- create a new "owner" account and assign to `terraform@<your-username>-terraform-admin.iam.gserviceaccount.com`
- set the project name in `variables.tf`

`<your-username>` is the Linux username from which you deploy Terraform.
