### ISSUE TITLE
Replace deprecated --addr and --port with --endpoint (v8-release only)

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#36]
Flags `--addr` and `--port` are deprecated. They should be replaced by `--endpoint`, such as:

`--endpoint "http://$NODE_HOST:$NODE_RPC_PORT"`

Here:
https://github.com/midl-dev/tezos-on-gke/blob/d971516ed823e51c689c3a0508eb9f518d4957b8/docker/tezos-baker-with-remote-signer/tezos-baker-with-remote-signer.sh#L30

and here:
https://github.com/midl-dev/tezos-on-gke/blob/d971516ed823e51c689c3a0508eb9f518d4957b8/docker/tezos-endorser-with-remote-signer/tezos-endorser-with-remote-signer.sh#L31

Edit: this flag will be available on `v8-release`.

**Comment by nicolasochem** [comment]
@denver-s @goodpen @marianogadea I just released v2.0-rc1, compatible with tezos 8.0 release, could you please check before I release in a few days?
See release notes https://github.com/midl-dev/tezos-on-gke/releases/tag/v2.0-rc1

**Comment by goodpen** [comment]
I can testing after holidays 3-4 January
