### ISSUE TITLE
Problems with tezos-sidecar

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#39]
Could not make it work with and without `experimental_active_standby_mode`.

With `experimental_active_standby_mode = false` I get this:

`rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/project-gcp/tezos-sidecar:tezos-latest not found: manifest unknown: Failed to fetch "tezos-latest" from request "/v2/project-gcp/tezos-sidecar/manifests/tezos-latest".: ErrImagePull`

**Comment by nicolasochem** [comment]
Solved? You need to rebuild all containers with `terraform taint null_resource.push_containers` uf you are upgrading.
